//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Calques3D.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define ID_WINDOW_MANAGER               102
#define IDS_WINDOW_MANAGER              103
#define IDR_MAINFRAME                   128
#define IDR_ABOUTDLG                    129
#define IDR_CONTEXT_MENU                130
#define IDR_POPUP_TOOLBAR               131
#define IDR_POPUP_MOVE                  132
#define IDR_UNDO                        138
#define IDR_VIEWUNIVERSE                140
#define IDR_VIEWMACRO                   141
#define IDR_VIEWHISTORIQUE              142
#define IDR_VIEWCALQUE                  143
#define IDR_VIEWGRAPH                   144
#define IDR_VIEWANALYTIC                145
#define IDR_VIEWDEPEND                  146
#define IDR_VIEWRENDERING               147
#define IDC_POINT                       153
#define IDC_POINTER_COPY                154
#define IDC_MOVE                        155
#define IDC_MOVE_VERT                   156
#define IDC_MOVE_HOR                    157
#define IDC_DROP_APPLY                  158
#define IDC_DROP_SELECT                 159
#define IDC_DROP_ERASE                  160
#define IDC_DROP_MARK                   161
#define IDC_DRAG                        162
#define IDR_POPUP_EXTRACT               164
#define IDR_OPEN                        166
#define IDR_POPUP_DEFAULT               167
#define IDR_POPUP_PROJECTION            168
#define IDR_POPUP_POINTOFVIEW           169
#define IDR_POPUP_SHAPE                 170
#define IDR_POPUP_MACRO                 171
#define IDR_CREDITS                     172
#define IDR_ZOOM                        173
#define IDR_REFERENTIEL                 174
#define IDR_POPUP_VERIFY                175
#define IDR_POPUP_MEASURE               176
#define IDR_POPUP_MATHPAD               178
#define IDC_PLACEHOLDER                 250
#define IDD_SUPPRESS_DLG                300
#define IDD_VERIFY_DLG                  301
#define IDD_SAVE_PROFILE_DLG            302
#define IDD_SPLASH                      303
#define IDD_MACROINFO_DLG               304
#define IDD_ZOOM_DLG                    305
#define IDD_UNDO_DLG                    306
#define IDD_POV_DLG                     307
#define IDD_OBJECTPROP_PAGE             311
#define IDD_OBJECTDEP_PAGE              312
#define IDD_OBJECTINFO_PAGE             313
#define IDD_OBJECTCPT_PAGE              314
#define IDD_OBJECTTEXT_PAGE             315
#define IDD_OBJECTFONT_PAGE             316
#define IDD_PREF_SESSION_PAGE           320
#define IDD_PREF_SHAPE_PAGE             321
#define IDD_PREF_COLORS_PAGE            322
#define IDD_PREF_UNIVERSE_PAGE          323
#define IDD_PREF_MACROS_PAGE            324
#define IDD_PREF_MATHPAD_PAGE           325
#define IDD_PREF_POV_PAGE               326
#define IDD_PREF_DISCOVERY_PAGE         327
#define IDD_PREF_HISTORY_PAGE           328
#define IDD_INPLACEEDIT                 330
#define IDD_ABOUTBOX                    331
#define IDD_ABOUTCREDIT                 332
#define IDD_ABOUTCALQUE                 333
#define IDD_ABOUTPROP                   334
#define IDD_RENDERER_PROP               335
#define IDD_MESSAGE                     340
#define IDB_SPLASH                      500
#define IDB_WORKSPACE                   501
#define IDB_SLIDERS                     502
#define IDB_VAR_ICONS                   503
#define IDB_BITMAP48                    504
#define IDB_MENU_LOGO                   505
#define IDB_LOGO                        506
#define IDB_MATHPAD                     507
#define IDB_LIST_ADDITEM                510
#define IDB_LIST_BROWSE                 511
#define IDB_LIST_DELITEM                512
#define IDB_PROJECTION                  513
#define IDB_OBJECTS_ICONS               514
#define IDB_BTNICON                     515
#define IDB_PREFBCG_ICONS               516
#define IDB_PREFC3D_ICONS               517
#define IDB_MSG_WARNING                 518
#define IDB_MSG_INFO                    519
#define IDB_MSG_TIPS                    520
#define IDR_MAINFRAME24                 600
#define IDR_COMMANDS_TB24               610
#define IDR_FORMAT_TB24                 615
#define IDR_PROPERTY_TB24               620
#define IDR_ALERT_TB24                  625
#define IDC_MAIL                        1000
#define IDC_URL                         1001
#define IDC_SUPPORT                     1002
#define IDC_BIGICON                     1023
#define IDC_FONT_COLOR                  1025
#define IDC_FONT_BOLD                   1038
#define IDC_FONT_FONTNAME               1039
#define IDC_FONT_FONTSIZE               1040
#define IDC_FONT_ITALIC                 1041
#define IDC_SUPP_SHOWLIST               1041
#define IDC_PROFILE_LIST                1041
#define IDC_FONT_UNDERLINE              1042
#define IDC_SUPP_DELETELIST             1042
#define IDC_OBJ_NAME                    1043
#define IDC_DMACRO_PATH                 1044
#define IDC_PROFILE_NAME                1044
#define IDC_OBJ_COLOR                   1045
#define IDC_OBJ_SHAPE                   1046
#define IDC_OBJ_HIDDEN                  1047
#define IDC_OBJ_MARK                    1048
#define IDC_OBJ_DEF                     1049
#define IDC_OBJ_HELP                    1050
#define IDC_SWITCH_MODE                 1050
#define IDC_OBJ_LOCUS                   1052
#define IDC_OBJ_LOCUSN                  1053
#define IDC_SHAPE_FREE                  1054
#define IDC_OBJ_LOCUSSPIN               1054
#define IDC_SHAPE_CSTR                  1055
#define IDC_SHAPE_CALC                  1056
#define IDC_SHAPE_VIS                   1057
#define IDC_SHAPE_DEFC                  1057
#define IDC_SHAPE_POINTSIZE             1058
#define IDC_SHAPE_SPINSIZE              1060
#define IDC_SHAPE_DEFCOLOR              1067
#define IDC_SHAPE_HIDDEN                1084
#define IDC_PUNIV_REFINIT               1098
#define IDC_PUNIV_MAGNET                1099
#define IDC_PUNIV_SYNCHRO               1100
#define IDC_VERSION                     1104
#define IDC_COPYRIGHT                   1105
#define IDC_DEBUG                       1106
#define IDC_INFO                        1107
#define IDC_PMAC_NAME                   1110
#define IDC_PMAC_DEF                    1111
#define IDC_PMAC_LOADMACRO              1112
#define IDC_PSESS_LIST                  1114
#define IDC_TAB                         1118
#define IDC_DMACRO_NAME                 1123
#define IDC_DMACRO_HELP                 1124
#define IDC_DMACRO_DEF                  1125
#define IDC_DMACRO_SAVEAS               1126
#define IDC_PSESS_DESCR                 1127
#define IDC_PUNIV_POVLIST               1130
#define IDC_OBJ_DEPLIST                 1131
#define IDC_ZOOM_SLIDER                 1132
#define IDC_ZOOM_VALUE                  1134
#define IDC_VERIFY_PROP_ICON            1135
#define IDC_VERIFY_PROP                 1136
#define IDC_VERIFY_OBJ1                 1138
#define IDC_VERIFY_OBJ2                 1139
#define IDC_VERIFY_RESULT               1140
#define IDC_VERIFY_COUNTER              1141
#define IDC_VERIFY_TOBJ1                1142
#define IDC_MATHPAD_REAL                1142
#define IDC_VERIFY_TOBJ2                1143
#define IDC_MATHPAD_FRACTION            1143
#define IDC_MATHPAD_SCALE               1144
#define IDC_MATHPAD_ANGLE               1145
#define IDC_MATHPAD_DIST                1146
#define IDC_MATHPAD_PRV                 1147
#define IDC_MATHPAD_PFR                 1148
#define IDC_MATHPAD_EXRV                1149
#define IDC_MATHPAD_EXFR                1150
#define IDC_TXT_EDIT                    1151
#define IDC_TXT_FONT                    1152
#define IDC_TXT_EQUATION                1153
#define IDC_TXT_VAR                     1154
#define IDC_TXT_VARNAME                 1155
#define IDC_VERIFY_TARGETS              1156
#define IDC_TXT_PALETTE                 1156
#define IDC_VERIFY_TARGET2              1157
#define IDC_VERIFY_TARGET               1157
#define IDC_SHAPE_APP                   1158
#define IDC_DISCOV_CAS                  1159
#define IDC_DISCOV_RUNTIME              1160
#define IDC_DISCOV_SCRIPT               1161
#define IDC_DISCOV_BROWSE               1162
#define IDC_DISCOV_BROWSECMD            1163
#define IDC_DISCOV_VERSION              1164
#define IDC_STATIC_CMD                  1165
#define IDC_STATIC_SCRIPT               1166
#define IDC_STATIC_NONE                 1168
#define IDC_UNDO_UNDO                   1169
#define IDC_UNDO_REDO                   1170
#define IDC_UNDO_TXT                    1171
#define IDC_PUNIV_TRACE                 1172
#define IDC_EDIT1                       1178
#define IDC_SPIN1                       1179
#define IDC_EDIT2                       1180
#define IDC_MESSAGE_CHECK               1181
#define IDC_SPIN2                       1183
#define IDC_MATHPAD_OPEN                1183
#define IDC_EDIT3                       1184
#define IDC_PUNIV_POLYGONS              1184
#define IDC_SPIN3                       1185
#define IDC_EDIT4                       1186
#define IDC_SPIN4                       1187
#define IDC_MESSAGE_STRING              1188
#define IDC_MESSAGE_IMG                 1189
#define IDC_PHISTO_SHOWSEL              1189
#define IDC_MESSAGE_TITLE               1190
#define IDC_POV_LIST                    1191
#define IDC_POV_THETA                   1192
#define IDC_POV_PHI                     1193
#define IDC_POV_INFO                    1194
#define IDC_ABOUTCALQUE                 1201
#define IDC_RENDERER_AMBTXT             1300
#define IDC_RENDERER_DIFFUSETXT         1301
#define IDC_RENDERER_SPECULARTXT        1302
#define IDC_RENDERER_LGTXTXT            1303
#define IDC_RENDERER_LGTYTXT            1304
#define IDC_RENDERER_LGTZTXT            1305
#define IDC_RENDERER_AMBIENT            1306
#define IDC_RENDERER_DIFFUSE            1307
#define IDC_RENDERER_SPECULAR           1308
#define IDC_RENDERER_SHINE              1309
#define IDC_RENDERER_LGTX               1310
#define IDC_RENDERER_LGTY               1311
#define IDC_RENDERER_LGTZ               1312
#define IDC_RENDERER_AMBMATTXT          1313
#define IDC_RENDERER_DIFFMATTXT         1314
#define IDC_RENDERER_SPECMATTXT         1315
#define IDC_RENDERER_AMBMAT             1316
#define IDC_RENDERER_DIFFMAT            1317
#define IDC_RENDERER_SPECMAT            1318
#define IDC_RENDERER_SHINETXT           1319
#define IDC_RENDERER_EMISSION           1320
#define IDC_RENDERER_EMISSIONTXT        1321
#define IDC_RENDERER_FIELDVIEW          1322
#define IDC_RENDERER_FIELDVIEWTXT       1323
#define IDS_LINESHAPE                   3000
#define IDS_LINESHAPE1                  3001
#define IDS_LINESHAPE2                  3002
#define IDS_LINESHAPE3                  3003
#define IDS_LINESHAPE4                  3004
#define IDS_LINESHAPE5                  3005
#define IDS_LINESHAPE6                  3006
#define IDS_LINESHAPE7                  3007
#define IDS_POINTSHAPE                  3010
#define IDS_POINTSHAPE1                 3011
#define IDS_POINTSHAPE2                 3012
#define IDS_POINTSHAPE3                 3013
#define IDS_POINTSHAPE4                 3014
#define IDS_POINTSHAPE5                 3015
#define IDS_VOLSHAPE                    3020
#define IDS_VOLSHAPE1                   3021
#define IDS_VOLSHAPE2                   3022
#define IDS_POLSHAPE                    3023
#define IDS_POLSHAPE1                   3024
#define IDS_POLSHAPE2                   3025
#define IDS_POLSHAPE3                   3026
#define IDS_POLSHAPE4                   3027
#define IDS_POLSHAPE5                   3028
#define IDS_POLSHAPE6                   3029
#define IDS_POLSHAPE7                   3030
#define IDS_POLSHAPE8                   3031
#define IDS_POLSHAPE9                   3032
#define IDS_AMBIGUITY                   3033
#define IDS_REDEFINE                    3034
#define IDS_NEWCOMMENT                  3050
#define IDS_MACROS                      3051
#define IDS_ABOUT_DONATE                3060
#define IDS_WARNING_TITLE               3500
#define ERR_SUPPORTOBJECT               4000
#define ERR_NOMIDDLE1                   4001
#define ERR_NOMIDDLE2                   4002
#define ERR_NOINTER                     4003
#define ERR_DROITEPAR                   4004
#define ERR_DROITNOCOPLAN               4005
#define ERR_INTERINSEG                  4006
#define ERR_DRPLANPAR                   4007
#define ERR_NOSPHERE                    4008
#define ERR_SPHPTSID                    4009
#define ERR_PTSALIGN                    4010
#define ERR_NOPLAN                      4011
#define ERR_NODROITE                    4012
#define ERR_DRPTSID                     4013
#define ERR_PLANEPAR                    4014
#define ERR_PTONLINE                    4015
#define ERR_2SAMEPTS                    4017
#define ERR_2SAMEDRS                    4018
#define ERR_2SAMEPLS                    4019
#define ERR_NOCERCLE                    4020
#define ERR_INDEPEND                    4021
#define ERR_CBPTSID                     4022
#define ERR_NOCYLIND                    4023
#define ERR_INTCALC                     4024
#define ERR_INTERSPHDR                  4025
#define ERR_LOCUS_NOREL                 4026
#define ERR_LOCUS_NOPTSUR               4027
#define ERR_NOLOCUS                     4028
#define ERR_LOCUS_INTERNAL              4029
#define ERR_REDEFINE_INGRAPH            4031
#define ERR_REDEFINE_PARENTS            4032
#define ERR_REDEFINE_NOPARENTS          4033
#define ERR_POLYGON_NOPLANE             4034
#define ERR_POLYGON_NOPLANE2            4035
#define ERR_POLYGON_3POINT              4036
#define ERR_NOPOLYGON                   4037
#define ERR_POLYGON_NOCONVEX            4038
#define ERR_AMBIGUITY                   4039
#define ERR_CIRCLELINE_NOTPLANE         4040
#define ERR_CIRCLEPLANE_PLANE           4041
#define ERR_INTER_SPHERESPHERE          4042
#define ERR_INTER_PLANESPHERE           4043
#define ERR_INTER_LINECIRCLE            4044
#define ERR_INTER_PLANECIRCLE           4045
#define ERR_CONE_UNDEFINED              4046
#define ERR_CONE_NORADIUS               4047
#define ERR_CONE_NOAXIS                 4048
#define ERR_CONE_NOPROJAXIS             4049
#define ERR_INTER_CONEDR                4050
#define IDS_UNDO_NONE                   4100
#define IDS_UNDO_DELETE                 4101
#define IDS_UNDO_APPEND                 4102
#define IDS_UNDO_MODIFY                 4103
#define IDS_UNDO_MOVE                   4104
#define IDS_UNDO_ULIST                  4150
#define IDS_UNDO_RLIST                  4151
#define VER_ERROR                       4200
#define VER_PAR_NO                      4201
#define VER_PAR_ANALYTIC                4202
#define VER_PAR_CONSTRUCTION            4203
#define VER_PERP_NO                     4204
#define VER_PERP_ANALYTIC               4205
#define VER_PERP_CONSTRUCTION           4206
#define VER_BELONG_NO                   4209
#define VER_BELONG_ANALYTIC             4210
#define VER_BELONG_CONSTRUCTION         4211
#define VER_ALIGN_NO                    4212
#define VER_ALIGN_ANALYTIC              4213
#define VER_ALIGN_CONSTRUCTION          4214
#define IDR_COMMANDS_TB                 4550
#define IDR_OBJECTS_TB                  4551
#define IDR_VISUALISATION_TB            4552
#define IDR_EXPLORATION_TB              4553
#define IDR_CONSTRUCTION_TB             4554
#define IDR_UNIVERSEH_TB                4556
#define IDR_UNIVERSEV_TB                4557
#define IDR_POINTON_TB                  4558
#define IDR_INTERSECT_TB                4559
#define IDR_POINTDIV_TB                 4560
#define IDR_GRAPH_TB                    4561
#define IDR_VERIFY_TB                   4562
#define IDR_PROPERTY_TB                 4566
#define IDR_DEPENDENT_TB                4567
#define IDR_FORMAT_TB                   4568
#define IDR_ALERT_TB                    4569
#define IDS_NAME_OBJECT                 5000
#define IDS_NAME_POINT                  5001
#define IDS_NAME_LINE                   5002
#define IDS_NAME_SEG                    5003
#define IDS_NAME_CIRCLE                 5004
#define IDS_NAME_PLANE                  5005
#define IDS_NAME_CUBE                   5006
#define IDS_NAME_SPHERE                 5007
#define IDS_NAME_CYLIN                  5008
#define IDS_NAME_CPTOBJECT              5009
#define IDS_NAME_TEXT                   5010
#define IDS_NAME_LOCUS                  5011
#define IDS_NAME_CONE                   5012
#define IDS_NAME_CONIC                  5013
#define IDS_NAME_VECTOR                 5099
#define IDS_HELP_OBJECT                 5100
#define IDS_HELP_POINT                  5101
#define IDS_HELP_LINE                   5102
#define IDS_HELP_SEG                    5103
#define IDS_HELP_CIRCLE                 5104
#define IDS_HELP_PLANE                  5105
#define IDS_HELP_SPHERE                 5107
#define IDS_HELP_CPTOBJECT              5108
#define IDS_HELP_CUBE                   5109
#define IDS_HELP_CYLIN                  5110
#define IDS_HELP_TEXT                   5111
#define IDS_HELP_LOCUS                  5112
#define IDS_HELP_VECTOR                 5113
#define IDS_HELP_POLYGON                5114
#define IDS_HELP_VALUE                  5115
#define IDS_HELP_ARCCIRCLE              5116
#define IDS_HELP_ELLIPSE                5117
#define IDS_HELP_RAY                    5118
#define IDS_HELP_EQUATION               5119
#define IDS_HELP_ANGLE                  5120
#define IDS_HELP_AREA                   5121
#define IDS_HELP_DISTANCE               5122
#define IDS_HELP_VOLUME                 5123
#define IDS_HELP_CONE                   5124
#define IDS_HELP_CONIC                  5125
#define IDS_DEF_OBJECT                  5200
#define IDS_DEF_POINT                   5201
#define IDS_DEF_POINTCALC               5202
#define IDS_DEF_POINTCENTER             5203
#define IDS_DEF_POINTIDD                5204
#define IDS_DEF_POINTIDP                5205
#define IDS_DEF_POINTMID                5206
#define IDS_DEF_POINTSUR                5207
#define IDS_DEF_POINTSYM                5208
#define IDS_DEF_POINTTRANS              5209
#define IDS_DEF_LINE                    5210
#define IDS_DEF_SEG                     5211
#define IDS_DEF_DEMIDR                  5212
#define IDS_DEF_DROITEIPP               5213
#define IDS_DEF_DROITEPAR               5214
#define IDS_DEF_DROITEPERP              5215
#define IDS_DEF_PLAN                    5216
#define IDS_DEF_PLANPERP                5217
#define IDS_DEF_CIRCLE                  5218
#define IDS_DEF_ARCCIRCLE               5219
#define IDS_DEF_POINTMID2               5220
#define IDS_DEF_CPTOBJECT               5221
#define IDS_DEF_CUBE                    5222
#define IDS_DEF_CYLIN                   5223
#define IDS_DEF_INTSPDR                 5224
#define IDS_DEF_TEXT                    5225
#define IDS_DEF_SPHERE                  5226
#define IDS_DEF_ELLIPSE                 5227
#define IDS_DEF_LOCUS                   5228
#define IDS_DEF_VECTOR                  5229
#define IDS_DEF_POLYGON                 5230
#define IDS_DEF_VALUE                   5231
#define IDS_DEF_ANGLE                   5232
#define IDS_DEF_DISTANCE                5233
#define IDS_DEF_LENGTH                  5234
#define IDS_DEF_AREA                    5235
#define IDS_DEF_VOLUME                  5236
#define IDS_DEF_CROSSPRODUCT            5237
#define IDS_DEF_CIRCLEISS               5238
#define IDS_DEF_SECTIONSEG              5239
#define IDS_DEF_INTCIRCDR               5240
#define IDS_DEF_INTCIRCPL               5241
#define IDS_DEF_CONE                    5242
#define IDS_DEF_INTCONEDR               5243
#define IDS_DEF_SPHERERADIUS            5244
#define CTX_DEFAULT                     6000
#define CTX_POINT                       6001
#define CTX_DROITE                      6003
#define CTX_SEGMENT                     6005
#define CTX_RAY                         6007
#define CTX_MOVE                        6010
#define CTX_DELETE_OBJECT               6012
#define CTX_PLAN                        6013
#define CTX_CIRCLE                      6016
#define CTX_SPHERE                      6017
#define CTX_INTERSECTION                6019
#define CTX_POINTSUR_DROITE             6020
#define CTX_MILIEU                      6021
#define CTX_CENTER_CIRCLE               6022
#define CTX_DROITE_PAR                  6023
#define CTX_DROITE_PERP                 6024
#define CTX_CUBE                        6025
#define CTX_POINT_INIT                  6026
#define CTX_POINT_DRAG                  6027
#define CTX_SELECT_POINT1               6028
#define CTX_SELECT_POINT2               6029
#define CTX_SELECT_POINT3               6030
#define CTX_SELECT_OBJECT               6031
#define CTX_DEFAULT_PROP                6032
#define CTX_MOVE_INIT                   6033
#define CTX_SELECT_DROITE               6034
#define CTX_SELECT_PLAN1                6035
#define CTX_SELECT_SPHERE               6036
#define CTX_SELECT_PLAN2                6037
#define CTX_SELECT_CIRCLE               6038
#define CTX_CUBE_ONCIRCLE               6039
#define CTX_CUBE_ORIENTATE              6040
#define CTX_POINTSUR_MOVE               6041
#define CTX_POINTSUR_PLAN               6042
#define CTX_POINTSUR_CERCLE             6043
#define CTX_POINTSUR_SPHERE             6044
#define CTX_SELECT_DROITE2              6045
#define CTX_DROITE_NORMAL               6046
#define CTX_PLAN_PERP                   6047
#define CTX_CYLINDER                    6048
#define CTX_EXTRACT_TASK                6049
#define CTX_SYMMETRIC                   6050
#define CTX_SELECT_SYM                  6051
#define CTX_TRANSLAT                    6052
#define CTX_PROJECTION                  6053
#define CTX_PROJECTION_SELECT           6054
#define CTX_PROJECTION_APPLY            6055
#define CTX_LABEL                       6056
#define CTX_COPYSHAPE                   6057
#define CTX_EQUATION                    6058
#define CTX_SELECT_POINTSEG             6059
#define CTX_GREFFE                      6060
#define CTX_REDEFINE                    6061
#define CTX_INTERSECTION_LL             6062
#define CTX_INTERSECTION_LP             6063
#define CTX_SELECT_DROITEPLAN           6064
#define CTX_CONE                        6065
#define CTX_SELECT_POINTANIM            6066
#define CTX_LOCUS                       6070
#define CTX_LOCUS_BASE                  6071
#define CTX_LOCUS_LOCUS                 6072
#define CTX_POLYGON                     6073
#define CTX_CROSSPRODUCT                6074
#define CTX_VERIFY                      6075
#define CTX_VERIFY_PROP                 6076
#define CTX_CENTERON                    6077
#define CTX_ANIMATION                   6078
#define CTX_MEASURE                     6079
#define CTX_MACRO_UNLOAD                6080
#define CTX_MACRO_POINT                 6081
#define CTX_MOVE_TRACE                  6082
#define CTX_SELECT_CLOSE_POLYGON        6083
#define CTX_SELECT_TASKOPTION           6084
#define CTX_SELECT_CONE                 6085
#define CTX_POINTSUR_CONE               6086
#define CTX_POINTSUR_CYL                6087
#define CTX_SELECT_CYL                  6088
#define PREF_NAME_PTFREE                7000
#define PREF_NAME_PTCSTR                7001
#define PREF_NAME_PTDEP                 7002
#define PREF_NAME_PTVIS                 7003
#define PREF_NAME_PTSIZE                7004
#define PREF_NAME_PT                    7005
#define PREF_NAME_SPH                   7006
#define PREF_NAME_COLOR                 7007
#define PREF_NAME_CLROTHER              7008
#define PREF_NAME_CLRAUTO               7009
#define PREF_NAME_SPHEQ                 7010
#define PREF_NAME_SPHGCR                7011
#define PREF_NAME_LOCUS                 7012
#define PREF_NAME_LOCSIZE               7013
#define PREF_NAME_LINE                  7014
#define PREF_NAME_CLRDOC                7015
#define PREF_NAME_CONE                  7016
#define PREF_NAME_CONEDBL               7017
#define PREF_DEF_PTFREE                 7100
#define PREF_DEF_PTCSTR                 7101
#define PREF_DEF_PTDEP                  7102
#define PREF_DEF_PTVIS                  7103
#define PREF_DEF_PTSIZE                 7104
#define PREF_DEF_PT                     7105
#define PREF_DEF_SPH                    7106
#define PREF_DEF_COLOR                  7107
#define PREF_DEF_CLROTHER               7108
#define PREF_DEF_CLRAUTO                7109
#define PREF_DEF_SPHEQ                  7110
#define PREF_DEF_SPHGCR                 7111
#define PREF_DEF_LOCUS                  7112
#define PREF_DEF_LOCSIZE                7113
#define PREF_DEF_LINE                   7114
#define PREF_DEF_CLRDOC                 7115
#define PREF_DEF_CONE                   7116
#define PREF_DEF_CONEDBL                7117
#define PROP_DEFINITION                 8000
#define PROP_APPEARANCE                 8001
#define PROP_OBJNAME                    8002
#define PROP_OBJCOLOR                   8003
#define PROP_OBJSHAPE                   8004
#define PROP_OBJVISIBLE                 8005
#define PROP_OBJMARKED                  8006
#define PROP_DEPENDENT                  8007
#define PROP_COMPOSITE                  8008
#define PROP_PARENTS                    8009
#define PROP_LOCUSSIZE                  8010
#define PROP_DEFINITION_DESC            8100
#define PROP_APPEARANCE_DESC            8101
#define PROP_OBJNAME_DESC               8102
#define PROP_OBJCOLOR_DESC              8103
#define PROP_OBJSHAPE_DESC              8104
#define PROP_OBJVISIBLE_DESC            8105
#define PROP_OBJMARKED_DESC             8106
#define PROP_DEPENDENT_DESC             8107
#define PROP_COMPOSITE_DESC             8108
#define PROP_PARENTS_DESC               8109
#define PROP_LOCUSSIZE_DESC             8110
#define IDC_PSESS_SAVEAS                18920
#define IDC_PMAC_LIST                   18921
#define IDC_PMAC_PATH                   18922
#define ID_VIEW_UNIVERSE                30000
#define ID_VIEW_HISTORIQUE              30001
#define ID_VIEW_GRAPH                   30002
#define ID_VIEW_ANALYTIC                30003
#define ID_VIEW_CALQUE                  30004
#define ID_VIEW_CALQUE2                 30005
#define ID_VIEW_CALQUE3                 30006
#define ID_VIEW_CALQUE4                 30007
#define ID_VIEW_RENDERING               30008
#define ID_VIEW_PLACEMENT_SAVE          30010
#define ID_VIEW_PLACEMENT_RESTORE       30011
#define ID_VIEW_CUSTOMIZE               30012
#define ID_VIEW_OPTIONS                 30013
#define ID_VIEW_USER_TOOLBAR1           30020
#define ID_VIEW_USER_TOOLBAR2           30021
#define ID_VIEW_USER_TOOLBAR3           30022
#define ID_VIEW_USER_TOOLBAR4           30023
#define ID_VIEW_USER_TOOLBAR5           30024
#define ID_VIEW_USER_TOOLBAR6           30025
#define ID_VIEW_USER_TOOLBAR7           30026
#define ID_VIEW_USER_TOOLBAR8           30027
#define ID_VIEW_USER_TOOLBAR9           30028
#define ID_VIEW_USER_TOOLBAR10          30029
#define ID_USER_TOOL1                   30030
#define ID_USER_TOOL2                   30031
#define ID_USER_TOOL3                   30032
#define ID_USER_TOOL4                   30033
#define ID_USER_TOOL5                   30034
#define ID_USER_TOOL6                   30035
#define ID_USER_TOOL7                   30036
#define ID_USER_TOOL8                   30037
#define ID_USER_TOOL9                   30038
#define ID_USER_TOOL10                  30039
#define ID_VISUALISATION_REFERENTIAL    30101
#define ID_VISUALISATION_REFERENTIAL_NONE 30102
#define ID_VISUALISATION_REFERENTIAL_AXES 30103
#define ID_VISUALISATION_REFERENTIAL_FLOOR 30104
#define ID_VISUALISATION_REFERENTIAL_WALLS 30105
#define ID_VISUALISATION_PERSPECTIVE    30106
#define ID_VISUALISATION_PERSPECTIVE_CAVALIERE 30107
#define ID_VISUALISATION_PERSPECTIVE_OBLIQUE 30108
#define ID_VISUALISATION_ZOOM           30109
#define ID_VISUALISATION_ZOOM_100       30110
#define ID_VISUALISATION_ZOOM_75        30111
#define ID_VISUALISATION_ZOOM_50        30112
#define ID_VISUALISATION_ZOOM_25        30113
#define ID_VISUALISATION_ZOOM_ADJUST    30114
#define ID_VISUALISATION_POV            30115
#define ID_VISUALISATION_POV_DEFINE     30116
#define ID_VISUALISATION_POV_DEFAULT    30117
#define ID_VISUALISATION_POV_POV1       30118
#define ID_VISUALISATION_POV_POV2       30119
#define ID_VISUALISATION_POV_POV3       30120
#define ID_VISUALISATION_POV_POV4       30121
#define ID_VISUALISATION_DEFAULTTASK    30122
#define ID_VISUALISATION_PROJECTION     30123
#define ID_VISUALISATION_CENTERON       30124
#define ID_VISUALISATION_APPLYSTYLE     30125
#define ID_VISUALISATION_ZOOM_150       30130
#define ID_VISUALISATION_SHOWMARKS      30150
#define ID_VISUALISATION_SHOWHIDDEN     30151
#define ID_VISUALISATION_PROJECTION_FRONT 30160
#define ID_VISUALISATION_PROJECTION_PROFIL 30161
#define ID_VISUALISATION_PROJECTION_MIRROR 30162
#define ID_VISUALISATION_PROJECTION_KEEPIT 30163
#define ID_VISUALISATION_POINTSOFVIEW   30170
#define ID_VISUALISATION_STYLE_COPY     30171
#define ID_VISUALISATION_STYLE_HIDE     30172
#define ID_VISUALISATION_STYLE_MARK     30173
#define ID_VISUALISATION_POV_HSLIDER    30175
#define ID_VISUALISATION_POV_VSLIDER    30176
#define ID_OBJECT_POINT                 30200
#define ID_OBJECT_SEGMENT               30201
#define ID_OBJECT_LINE                  30202
#define ID_OBJECT_RAY                   30203
#define ID_OBJECT_CIRCLE                30204
#define ID_OBJECT_ARCCIRCLE             30205
#define ID_OBJECT_PLANE                 30206
#define ID_OBJECT_VOLUME                30207
#define ID_OBJECT_CUBE                  30208
#define ID_OBJECT_SPHERE                30209
#define ID_OBJECT_CYLINDRE              30210
#define ID_OBJECT_DELETE                30211
#define ID_OBJECT_REDEFINE              30212
#define ID_OBJECT_POLYGON               30213
#define ID_OBJECT_CONE                  30214
#define ID_CONSTRUCTION_POINTON         30310
#define ID_CONSTRUCTION_POINTON_LINE    30311
#define ID_CONSTRUCTION_POINTON_CIRCLE  30312
#define ID_CONSTRUCTION_POINTON_PLANE   30313
#define ID_CONSTRUCTION_POINTON_SPHERE  30314
#define ID_CONSTRUCTION_POINTON_CYLINDER 30315
#define ID_CONSTRUCTION_POINTON_CONE    30316
#define ID_CONSTRUCTION_INTERSECTION    30320
#define ID_CONSTRUCTION_INTERSECTION_LINELINE 30321
#define ID_CONSTRUCTION_INTERSECTION_LINEPLANE 30322
#define ID_CONSTRUCTION_INTERSECTION_LINESPHERE 30323
#define ID_CONSTRUCTION_INTERSECTION_PLANEPLANE 30324
#define ID_CONSTRUCTION_INTERSECTION_PLANECYLINDER 30325
#define ID_CONSTRUCTION_INTERSECTION_SPHERESPHERE 30326
#define ID_CONSTRUCTION_INTERSECTION_LINECIRCLE 30327
#define ID_CONSTRUCTION_INTERSECTION_PLANECIRCLE 30328
#define ID_CONSTRUCTION_INTERSECTION_SPHEREPLANE 30329
#define ID_CONSTRUCTION_INTERSECTION_LINECONE 30330
#define ID_CONSTRUCTION_INTERSECTION_PLANECONE 30331
#define ID_CONSTRUCTION_MIDPOINT        30340
#define ID_CONSTRUCTION_CENTER          30341
#define ID_CONSTRUCTION_PARALLELLINE    30342
#define ID_CONSTRUCTION_PERPENDICULARLINE 30343
#define ID_CONSTRUCTION_PERPENDICULARPLANE 30344
#define ID_CONSTRUCTION_NORMALLINE      30345
#define ID_CONSTRUCTION_SYMMETRICALPOINT 30346
#define ID_CONSTRUCTION_TRANSLATION     30347
#define ID_CONSTRUCTION_CROSSPRODUCT    30348
#define ID_CONSTRUCTION_DIVSEGMENT      30349
#define ID_EXPLORATION_MOVE             30400
#define ID_EXPLORATION_EXTRACTION       30401
#define ID_EXPLORATION_LOCUS            30402
#define ID_EXPLORATION_LABEL            30403
#define ID_EXPLORATION_EQUATION         30404
#define ID_EXPLORATION_MEASURE          30405
#define ID_EXPLORATION_VERIFY           30406
#define ID_EXPLORATION_INFORMATION      30407
#define ID_EXPLORATION_ANIMATION        30408
#define ID_EXPLORATION_DISCOVERY        30409
#define ID_EXPLORATION_EXTRACTION_CALQUE1 30450
#define ID_EXPLORATION_EXTRACTION_CALQUE2 30451
#define ID_EXPLORATION_EXTRACTION_CALQUE3 30452
#define ID_EXPLORATION_EXTRACTION_CALQUE4 30453
#define ID_EXPLORATION_EXTRACTION_ADDALL 30454
#define ID_EXPLORATION_EXTRACTION_REMOVEFROM 30455
#define ID_EXPLORATION_EXTRACTION_REMOVEALL 30456
#define ID_EXPLORATION_EXTRACTION_ADDIN 30457
#define ID_EXPLORATION_MOVE_MAGNETISM   30460
#define ID_EXPLORATION_MOVE_HORIZONTAL  30461
#define ID_EXPLORATION_MOVE_LEFT        30462
#define ID_EXPLORATION_MOVE_RIGTH       30463
#define ID_EXPLORATION_MOVE_TRACE       30464
#define ID_EXPLORATION_VERIFY_PAR       30470
#define ID_EXPLORATION_VERIFY_PERP      30471
#define ID_EXPLORATION_VERIFY_PTON      30472
#define ID_EXPLORATION_VERIFY_PTALIGN   30473
#define ID_EXPLORATION_MEASURE_DISTANCE 30480
#define ID_EXPLORATION_MEASURE_ANGLE    30481
#define ID_EXPLORATION_MEASURE_VOLUME   30482
#define ID_EXPLORATION_MEASURE_AREA     30483
#define ID_EXPLORATION_MEASURE_LENGTH   30484
#define ID_MACROS_SAVE                  30500
#define ID_MACROS_LOAD                  30501
#define ID_MACROS_INFO                  30502
#define ID_MACROS_USERS                 30510
#define ID_MACROS_USER1                 30550
#define ID_MACROS_USER2                 30551
#define ID_MACROS_USER3                 30552
#define ID_MACROS_USER4                 30553
#define ID_MACROS_USER5                 30554
#define ID_MACROS_USER6                 30555
#define ID_MACROS_USER7                 30556
#define ID_MACROS_USER8                 30557
#define ID_MACROS_USER9                 30558
#define ID_MACROS_USER10                30559
#define ID_MACROS_USER11                30560
#define ID_MACROS_USER12                30561
#define ID_MACROS_USER13                30562
#define ID_MACROS_USER14                30563
#define ID_MACROS_USER15                30564
#define ID_HISTORY_EXPORTSYMBOLIC       30600
#define ID_HISTORY_EXPANDALL            30601
#define ID_HISTORY_COLLAPSEALL          30602
#define ID_HISTORY_PROPERTY             30603
#define ID_GRAPH_SHOWPARENTS            30700
#define ID_GRAPH_SHOWCHILDREN           30701
#define ID_GRAPH_SHOWDEPENDENTS         30702
#define ID_GRAPH_SHOWBASEPT             30703
#define ID_MATHPAD_ADDCOMMENT           30800
#define ID_MATHPAD_ADDEQUATION          30801
#define ID_MATHPAD_LISTVARS             30802
#define ID_RENDERER_PROPERTY            30900
#define ID_RENDERER_SILHOUETTE          30901
#define ID_RENDERER_FILL                30902
#define ID_RENDERER_STIPPLE             30903
#define ID_ALERT_WARNING                31100
#define ID_ALERT_INFO                   31101
#define ID_ALERT_HELP                   31102
#define ID_ALERT_TIP                    31103
#define ID_VIEW_TOOLBARS                32771
#define ID_FORMAT_OBJCOLOR              32800
#define ID_FORMAT_OBJSHAPE              32801
#define ID_FORMAT_TXTFONT               32802
#define ID_FORMAT_TXTSIZE               32803
#define ID_FORMAT_TXTCOLOR              32804
#define ID_FORMAT_BOLD                  32805
#define ID_FORMAT_ITALIC                32806
#define ID_FORMAT_UNDERLINE             32807
#define ID_TOOLS_ENTRY                  32830
#define ID_VIEW_APPLOOK_2000            32833
#define ID_VIEW_APPLOOK_XP              32834
#define ID_VIEW_APPLOOK_2003            32835
#define ID_VIEW_APPLOOK_WIN_XP          32836
#define ID_VIEW_APPLOOK_VS2005          32837
#define ID_VIEW_FULLSCREEN              32839
#define ID_VISUALISATION_HORSLIDER      32841
#define ID_VISUALISATION_VERSLIDER      32842
#define ID_HELP_KEYBOARDMAP             32845
#define ID_PROPERTY_EXPAND              32878
#define ID_PROPERTY_SORTING             32879
#define ID_EDIT_UNDO_DELETE             32907
#define ID_EDIT_UNDO_APPEND             32908
#define ID_EDIT_UNDO_MODIFY             32909
#define ID_EDIT_UNDO_DUMMY              32915
#define ID_EDIT_UNDO_MORE               32916
#define ID_VIEW_OBJECT                  32927
#define ID_VIEW_CONSTRUCTION            32930
#define ID_VIEW_VISUALISATION           32931
#define ID_VIEW_EXPLORATION             32932
#define ID_VIEW_PROPERTYBAR             32933
#define ID_VIEW_DEPENDENTBAR            32934
#define ID_VIEW_FORMAT                  32935
#define ID_DUMMY_POINTON                32960
#define ID_DUMMY_INTERS                 32961
#define ID_DUMMY_POINTDIV               32962
#define ID_SESSION_DEF                  32991
#define ID_SESSION_DESCR                32992
#define ID_FREE_TEAROFF1                32993
#define ID_FREE_TEAROFF2                32994
#define AFX_IDS_OBJPROP                 57347
#define ID_INDICATOR_MODE               0xE707
#define ID_INDICATOR_ICON               59144
#define ID_INDICATOR_PROGRESS           59145
#define AFX_IDP_C3D_OLDVERSION          0xF10F

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32998
#define _APS_NEXT_CONTROL_VALUE         1195
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
